// <auto-generated>
// This file is generated automatically by UnityCliRunner.
// To generate or refresh this file in case of an update, open your Unity Editor and run:
// Tools > UnityCliRunner > Install MCP Configurations
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

string? projectPath = null;
var remainingArgs = new List<string>();

for (int i = 0; i < args.Length; i++)
{
    if ((args[i] == "--project" || args[i] == "-p") && i + 1 < args.Length)
    {
        projectPath = args[++i];
    }
    else
    {
        remainingArgs.Add(args[i]);
    }
}

if (string.IsNullOrWhiteSpace(projectPath))
{
    projectPath = Environment.GetEnvironmentVariable("UNITY_CLI_PROJECT_ROOT");
}

if (string.IsNullOrWhiteSpace(projectPath))
{
    projectPath = AutoDetectUnityProject();
}

string resolvedProjectPath = Path.GetFullPath(projectPath);
string? mcpDll = FindMcpDll(resolvedProjectPath);

if (string.IsNullOrEmpty(mcpDll) || !File.Exists(mcpDll))
{
    Console.Error.WriteLine($"[UnityCliRunner] Error: UnityCliRunner package was not found for Unity project at:");
    Console.Error.WriteLine($"  '{resolvedProjectPath}'");
    Console.Error.WriteLine("Please open the project in the Unity Editor to restore packages.");
    return 1;
}

string mcpDir = Path.GetDirectoryName(mcpDll)!;

var psi = new ProcessStartInfo
{
    FileName = "dotnet",
    WorkingDirectory = mcpDir,
    UseShellExecute = false,
    RedirectStandardInput = true,
    RedirectStandardOutput = true,
    RedirectStandardError = true,
};

psi.ArgumentList.Add(mcpDll);
psi.ArgumentList.Add("--project");
psi.ArgumentList.Add(resolvedProjectPath);
foreach (var arg in remainingArgs)
{
    psi.ArgumentList.Add(arg);
}

using var proc = Process.Start(psi);
if (proc == null)
{
    Console.Error.WriteLine("[UnityCliRunner] Error: Failed to spawn dotnet process.");
    return 1;
}

using var cts = new CancellationTokenSource();

Console.CancelKeyPress += (_, e) =>
{
    e.Cancel = true;
    cts.Cancel();
    try { if (!proc.HasExited) proc.Kill(true); } catch { }
};

AppDomain.CurrentDomain.ProcessExit += (_, _) =>
{
    try { if (!proc.HasExited) proc.Kill(true); } catch { }
};

var stdoutTask = ForwardStreamAsync(proc.StandardOutput.BaseStream, Console.OpenStandardOutput(), cts.Token);
var stderrTask = ForwardStreamAsync(proc.StandardError.BaseStream, Console.OpenStandardError(), cts.Token);
var stdinTask = ForwardStdinAsync(Console.OpenStandardInput(), proc.StandardInput.BaseStream, proc, cts.Token);

await proc.WaitForExitAsync();
cts.Cancel();

try
{
    await Task.WhenAll(stdoutTask, stderrTask);
}
catch { }

return proc.ExitCode;

static string AutoDetectUnityProject()
{
    string current = Directory.GetCurrentDirectory();
    var dir = new DirectoryInfo(current);
    while (dir != null)
    {
        if (IsUnityProject(dir.FullName))
        {
            return dir.FullName;
        }

        string candidate = Path.Combine(dir.FullName, "src", "UnityCliRunner.Unity3d");
        if (IsUnityProject(candidate))
        {
            return candidate;
        }

        dir = dir.Parent;
    }

    // Search subdirectories up to depth 3
    try
    {
        var rootDir = new DirectoryInfo(current);
        foreach (var sub in rootDir.GetDirectories())
        {
            if (sub.Name.StartsWith(".") || sub.Name == "Library" || sub.Name == "Temp" || sub.Name == "bin" || sub.Name == "obj")
            {
                continue;
            }

            if (IsUnityProject(sub.FullName))
            {
                return sub.FullName;
            }

            try
            {
                foreach (var sub2 in sub.GetDirectories())
                {
                    if (sub2.Name.StartsWith(".") || sub2.Name == "Library" || sub2.Name == "Temp" || sub2.Name == "bin" || sub2.Name == "obj")
                    {
                        continue;
                    }

                    if (IsUnityProject(sub2.FullName))
                    {
                        return sub2.FullName;
                    }
                }
            }
            catch { }
        }
    }
    catch { }

    return current;
}

static bool IsUnityProject(string path)
{
    return Directory.Exists(Path.Combine(path, "Assets")) &&
           Directory.Exists(Path.Combine(path, "ProjectSettings"));
}

static string? FindMcpDll(string unityProjectPath)
{
    // 1. Embedded package
    string[] embeddedPaths = new[]
    {
        Path.Combine(unityProjectPath, "Packages", "com.pereviader.unityclirunner", "MCP~", "UnityCliRunner.Mcp.dll"),
        Path.Combine(unityProjectPath, "Packages", "com.pereviader.unityclirunner", "MCP", "UnityCliRunner.Mcp.dll")
    };
    foreach (var p in embeddedPaths)
    {
        if (File.Exists(p)) return p;
    }

    // 2. PackageCache
    string packageCache = Path.Combine(unityProjectPath, "Library", "PackageCache");
    if (Directory.Exists(packageCache))
    {
        try
        {
            var matchingDirs = new DirectoryInfo(packageCache)
                .GetDirectories("com.pereviader.unityclirunner*")
                .OrderByDescending(d => d.LastWriteTimeUtc);

            foreach (var d in matchingDirs)
            {
                string dll1 = Path.Combine(d.FullName, "MCP~", "UnityCliRunner.Mcp.dll");
                if (File.Exists(dll1)) return dll1;

                string dll2 = Path.Combine(d.FullName, "MCP", "UnityCliRunner.Mcp.dll");
                if (File.Exists(dll2)) return dll2;
            }
        }
        catch { }
    }

    // 3. Check manifest.json for local file: references
    string manifestPath = Path.Combine(unityProjectPath, "Packages", "manifest.json");
    if (File.Exists(manifestPath))
    {
        try
        {
            string manifestText = File.ReadAllText(manifestPath);
            const string searchKey = "\"com.pereviader.unityclirunner\"";
            int keyIdx = manifestText.IndexOf(searchKey, StringComparison.Ordinal);
            if (keyIdx != -1)
            {
                int fileIdx = manifestText.IndexOf("\"file:", keyIdx, StringComparison.Ordinal);
                if (fileIdx != -1 && fileIdx < manifestText.IndexOf('\n', keyIdx))
                {
                    int start = fileIdx + 6;
                    int end = manifestText.IndexOf('"', start);
                    if (end != -1)
                    {
                        string rel = manifestText.Substring(start, end - start);
                        string packagesFolder = Path.Combine(unityProjectPath, "Packages");
                        string resolved = Path.GetFullPath(Path.Combine(packagesFolder, rel));
                        string dll1 = Path.Combine(resolved, "MCP~", "UnityCliRunner.Mcp.dll");
                        if (File.Exists(dll1)) return dll1;
                        string dll2 = Path.Combine(resolved, "MCP", "UnityCliRunner.Mcp.dll");
                        if (File.Exists(dll2)) return dll2;
                    }
                }
            }
        }
        catch { }
    }

    return null;
}

static async Task ForwardStreamAsync(Stream source, Stream destination, CancellationToken ct)
{
    byte[] buffer = new byte[4096];
    try
    {
        int bytesRead;
        while ((bytesRead = await source.ReadAsync(buffer, 0, buffer.Length, ct)) > 0)
        {
            await destination.WriteAsync(buffer, 0, bytesRead, ct);
            await destination.FlushAsync(ct);
        }
    }
    catch (OperationCanceledException) { }
    catch (Exception) { }
}

static async Task ForwardStdinAsync(Stream source, Stream destination, Process proc, CancellationToken ct)
{
    byte[] buffer = new byte[4096];
    try
    {
        int bytesRead;
        while (!ct.IsCancellationRequested && (bytesRead = await source.ReadAsync(buffer, 0, buffer.Length, ct)) > 0)
        {
            await destination.WriteAsync(buffer, 0, bytesRead, ct);
            await destination.FlushAsync(ct);
        }
    }
    catch (OperationCanceledException) { }
    catch (Exception) { }
    finally
    {
        try { proc.StandardInput.Close(); } catch { }
    }
}
